name: Build and Test

on:
  push:
    branches:
      - main
      - feature/"
    Tags:
      - v"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test
